typo fix

diff --git a/bin/gut b/bin/gut
--- a/bin/gut
+++ b/bin/gut
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+DIR=.
+
 while [ "$1" != "" ]
 do
     case "$1" in
@@ -7,11 +9,16 @@ do
             HIDE="| grep -v -e \"~$\" -e \".pyc$\" "
             ;;
         *)
-            echo "SYNTAX ERROR: $1"
-            exit 1
+            DIR=$1
             ;;
     esac
     shift
 done
 
+cd $DIR
+if [ $? -ne 0 ]
+then
+    echo "Directory not existing or permissons are missing"
+    exit 1
+fi
 echo "git ls-files --others --exclude-standard $HIDE" | bash
